### ISSUE TITLE
Authentication Issues

### ISSUE THREAD

**Issue by AAllport** [activecollab/activecollab-feather-sdk#22]
Hi, there seams to be some issue with the cloud authentication.
Started this morning, when the new version of AC was released

```
ActiveCollab\SDK\Exceptions\Authentication: Invalid response
```

Looking deeper into the issue, seams to be related to the `/api/v1/external/login` endpoint

**Comment by bumbus** [comment]
It looks like todays AC update did break at least the login endpoint, https://my.activecollab.com/api/v1/external/login:

```
Slim Application Error
The application could not run because of the following error:

Details
Type: RuntimeException
Message: Failed to parse response. Reason: unexpected character
File: /var/www/acid/app/controllers/ExternalController.class.php
Line: 109
Trace
#0 /var/www/acid/app/controllers/ExternalController.class.php(91): ExternalController->executeCurlRequest(Resource id 
#8)
#1 /var/www/acid/app/controllers/ExternalController.class.php(52): ExternalController->getTokenFromNewShepherd(Array)
#2 /var/www/acid/app/controllers/ExternalController.class.php(23): ExternalController->getLoginDataNewShepherd(Array)
#3 [internal function]: ExternalController->login()
#4 /var/www/acid/lib/Controller.class.php(84): call_user_func_array(Array, Array)
#5 /var/www/acid/config/routes.php(80): Controller::execute('external', 'login')
#6 [internal function]: {closure}()
#7 /var/www/acid/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#8 /var/www/acid/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#9 /var/www/acid/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#10 /var/www/acid/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#11 /var/www/acid/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#12 /var/www/acid/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#13 /var/www/acid/frontend/router.php(48): Slim\Slim->run()
#14 {main}
```

**Comment by AAllport** [comment]
You got an ETA for the fix?

**Comment by ilijastuden** [comment]
Authentication backends have been updated, and tested. Things look from here now.

**Comment by AAllport** [comment]
Can confirm, working for us

**Comment by ilijastuden** [comment]
Great, thanks. Sorry for the trouble.
